import { Translation, Section, Module, Language } from './types';

export const I18N: Translation = {
  es: {
    langLabel: "Idioma:",
    appTitle: "Asistente Genético",
    submitButton: "Generar Resultado",
    loadingText: "Procesando, por favor espere...",
    responseTitle: "Respuesta del Asistente AI",
    emptyResponse: "La respuesta del asistente aparecerá aquí.",
    emptyInputError: "Por favor, complete todos los campos de entrada.",
    exportAlert: "No hay contenido para exportar. Por favor, genere una respuesta primero.",
    disclaimer: "Gemini puede cometer errores, así que verifica las respuestas.",
    printTitle: "Imprimir Resultado",
    exportPngTitle: "Exportar como PNG",
    exportJpgTitle: "Exportar como JPG",
    section_assistance_title: "🧠 Asistencia y Soporte Inteligente",
    section_analysis_title: "🧪 Herramientas de Evaluación y Análisis",
    section_query_title: "🧬 Consulta de Información Biomolecular",
    section_education_title: "📚 Materiales Educativos y Referenciales",
    asistente_title: "Asistente Virtual de Genética",
    asistente_desc: "Responda preguntas frecuentes de genética.",
    asistente_input_label: "Su pregunta",
    asistente_placeholder: "Escriba aquí su consulta...",
    evaluador_title: "Evaluador Preliminar",
    evaluador_desc: "Estime si un paciente debe ser referido a genética clínica.",
    evaluador_summary_label: "Resumen Clínico",
    evaluador_summary_placeholder: "Ej: Paciente de 5 años con hipotonía...",
    evaluador_history_label: "Antecedentes Familiares",
    evaluador_history_placeholder: "Ej: Padres no consanguíneos...",
    interprete_title: "Intérprete de Reportes Genéticos",
    interprete_desc: "Convierta un reporte de laboratorio en un resumen entendible.",
    interprete_input_label: "Pegue el contenido del reporte (VCF, texto, etc.)",
    interprete_placeholder: "##fileformat=VCFv4.2...",
    simulador_title: "Simulador de Consejería Genética",
    simulador_desc: "Entrene habilidades de comunicación en escenarios de consejo genético.",
    simulador_scenario_label: "Seleccione un Escenario",
    simulador_message_label: "Su primera frase",
    simulador_message_placeholder: "Ej: Hola, gracias por venir...",
    reuniones_title: "Apoyo en Reuniones",
    reuniones_desc: "Responda preguntas contextuales sobre genes y síndromes.",
    reuniones_input_label: "Su pregunta",
    reuniones_placeholder: "Escriba aquí su consulta...",
    generador_title: "Generador de Informes",
    generador_desc: "Redacte cartas para pacientes a partir de reportes técnicos.",
    generador_clinical_label: "Datos Clínicos Relevantes",
    generador_clinical_placeholder: "Ej: Paciente: Juan Pérez, 32 años...",
    generador_molecular_label: "Resultado Molecular (Técnico)",
    generador_molecular_placeholder: "Ej: Gen: CFTR. Variante: c.1521_1523delCTT...",
    genes_title: "Genes",
    genes_desc: "Busque información detallada sobre un gen específico.",
    genes_input_label: "Símbolo del Gen (ej. CFTR)",
    genes_placeholder: "Ingrese el símbolo oficial del gen...",
    proteinas_title: "Proteínas",
    proteinas_desc: "Busque información sobre una proteína, sus dominios y variantes.",
    proteinas_input_label: "Nombre de la Proteína o ID de UniProt",
    proteinas_placeholder: "Ingrese el nombre de la proteína...",
    vias_de_señalizacion_title: "Vías de señalización",
    vias_de_señalizacion_desc: "Explore vías de señalización metabólicas y los genes involucrados.",
    vias_de_señalizacion_input_label: "Gen o Vía de Señalización",
    vias_de_señalizacion_placeholder: "Ingrese un gen (ej. AKT1) o una vía (ej. MAPK signaling pathway)...",
    glosario_title: "Glosario Genético Interactivo",
    glosario_desc: "Defina términos genéticos complejos de forma sencilla.",
    glosario_input_label: "Término a definir",
    glosario_placeholder: "Ingrese un término genético...",
    autoevaluacion_title: "Autoevaluación",
    autoevaluacion_button: "Generar Autoevaluación",
    autoevaluacion_desc: "Pon a prueba tus conocimientos sobre el tema consultado.",
    print_quiz_button: "Imprimir Cuestionario",
    login_button: "Iniciar Sesión con Google",
    logout_button: "Cerrar Sesión",
    history_title: "Historial de Consultas",
    no_history: "No hay consultas previas.",
    patologias_title: "Patologías Genéticas",
    patologias_desc: "Consulta de enfermedades de base genética.",
    patologias_input_label: "Nombre de la patología o síndrome",
    patologias_placeholder: "Ej: Síndrome de Marfan, Fibrosis Quística...",
    epigenetica_title: "Epigenética",
    epigenetica_desc: "Consulta sobre mecanismos epigenéticos y regulación.",
    epigenetica_input_label: "Mecanismo o concepto epigenético",
    epigenetica_placeholder: "Ej: Metilación del ADN, Imprinting...",
    section_admin_title: "📊 Administración y Métricas",
    analytics_title: "Panel de Analítica",
    analytics_desc: "Visualice métricas de uso y feedback de usuarios.",
    feedback_button: "Dar Feedback",
    feedback_title: "Tu opinión nos importa",
    feedback_desc: "¿Cómo calificarías esta respuesta?",
    feedback_submit: "Enviar Feedback",
    feedback_success: "¡Gracias por tu feedback!",
    feedback_provider_invite: "También puedes realizar un feedback discriminado por proveedor de Agente IA, si lo consideras oportuno.",
    analytics_usage_by_mode_desc: "Este gráfico muestra la distribución de tus consultas entre los diferentes módulos del asistente. Te permite identificar qué herramientas estás utilizando con más frecuencia.",
    metric_functionality_desc: "Evalúa si la IA siguió las instrucciones, estructuró la respuesta correctamente y cumplió con el formato solicitado.",
    metric_accuracy_desc: "Mide la exactitud técnica y científica de la información clínica y genética proporcionada.",
    metric_relevance_desc: "Califica qué tan bien se ajustan los enlaces, referencias y datos al caso específico consultado.",
    metric_usability_desc: "Evalúa la claridad del lenguaje y qué tan fácil es de entender para el profesional o el paciente.",
    metric_satisfaction_desc: "Representa la experiencia general y la utilidad percibida de la respuesta entregada.",
    metric_explanation_title: "Explicación de Métricas",
  },
  en: {
    langLabel: "Language:",
    appTitle: "Genetic Assistant",
    submitButton: "Generate Result",
    loadingText: "Processing, please wait...",
    responseTitle: "Response from the AI Assistant",
    emptyResponse: "The assistant's response will appear here.",
    emptyInputError: "Please fill in all input fields.",
    exportAlert: "There is no content to export. Please generate a response first.",
    disclaimer: "Gemini can make mistakes, so please double-check its responses.",
    analytics_usage_by_mode_desc: "This chart shows the distribution of your queries across the different assistant modules. It allows you to identify which tools you are using most frequently.",
    metric_functionality_desc: "Evaluates if the AI followed instructions, structured the response correctly, and met the requested format.",
    metric_accuracy_desc: "Measures the technical and scientific accuracy of the clinical and genetic information provided.",
    metric_relevance_desc: "Rates how well the links, references, and data fit the specific case consulted.",
    metric_usability_desc: "Evaluates the clarity of the language and how easy it is for the professional or patient to understand.",
    metric_satisfaction_desc: "Represents the overall experience and perceived utility of the delivered response.",
    metric_explanation_title: "Metrics Explanation",
    printTitle: "Print Result",
    exportPngTitle: "Export as PNG",
    exportJpgTitle: "Export as JPG",
    section_assistance_title: "🧠 Intelligent Assistance & Support",
    section_analysis_title: "🧪 Evaluation & Analysis Tools",
    section_query_title: "🧬 Biomolecular Information Query",
    section_education_title: "📚 Educational & Reference Materials",
    asistente_title: "Virtual Genetic Assistant",
    asistente_desc: "Answer frequently asked questions about genetics.",
    asistente_input_label: "Your question",
    asistente_placeholder: "Type your query here...",
    evaluador_title: "Preliminary Evaluator",
    evaluador_desc: "Estimate if a patient should be referred to clinical genetics.",
    evaluador_summary_label: "Clinical Summary",
    evaluador_summary_placeholder: "e.g., 5-year-old patient with hypotonia...",
    evaluador_history_label: "Family History",
    evaluador_history_placeholder: "e.g., Non-consanguineous parents...",
    interprete_title: "Genetic Report Interpreter",
    interprete_desc: "Turn a lab report into an understandable summary.",
    interprete_input_label: "Paste the report content (VCF, text, etc.)",
    interprete_placeholder: "##fileformat=VCFv4.2...",
    simulador_title: "Genetic Counseling Simulator",
    simulador_desc: "Train communication skills in genetic counseling scenarios.",
    simulador_scenario_label: "Select a Scenario",
    simulador_message_label: "Your opening line",
    simulador_message_placeholder: "e.g., Hello, thanks for coming in...",
    reuniones_title: "Meeting Support",
    reuniones_desc: "Answer contextual questions about genes and syndromes.",
    reuniones_input_label: "Your question",
    reuniones_placeholder: "Type your query here...",
    generador_title: "Report Generator",
    generador_desc: "Draft letters for patients from technical reports.",
    generador_clinical_label: "Relevant Clinical Data",
    generador_clinical_placeholder: "e.g., Patient: John Doe, 32 years old...",
    generador_molecular_label: "Molecular Result (Technical)",
    generador_molecular_placeholder: "e.g., Gene: CFTR. Variant: c.1521_1523delCTT...",
    genes_title: "Genes",
    genes_desc: "Look up detailed information about a specific gene.",
    genes_input_label: "Gene Symbol (e.g., CFTR)",
    genes_placeholder: "Enter the official gene symbol...",
    proteinas_title: "Proteins",
    proteinas_desc: "Find information about a protein, its domains, and variants.",
    proteinas_input_label: "Protein Name or UniProt ID",
    proteinas_placeholder: "Enter the protein name...",
    vias_de_señalizacion_title: "Signaling Pathways",
    vias_de_señalizacion_desc: "Explore metabolic signaling pathways and the genes involved.",
    vias_de_señalizacion_input_label: "Gene or Signaling Pathway",
    vias_de_señalizacion_placeholder: "Enter a gene (e.g., AKT1) or a pathway (e.g., MAPK signaling pathway)...",
    glosario_title: "Interactive Genetic Glossary",
    glosario_desc: "Define complex genetic terms in a simple way.",
    glosario_input_label: "Term to define",
    glosario_placeholder: "Enter a genetic term...",
    autoevaluacion_title: "Self-Assessment",
    autoevaluacion_button: "Generate Self-Assessment",
    autoevaluacion_desc: "Test your knowledge on the queried topic.",
    print_quiz_button: "Print Quiz",
    login_button: "Login with Google",
    logout_button: "Logout",
    history_title: "Query History",
    no_history: "No previous queries.",
    patologias_title: "Genetic Pathologies",
    patologias_desc: "Query for diseases with a genetic basis.",
    patologias_input_label: "Pathology or syndrome name",
    patologias_placeholder: "e.g., Marfan Syndrome, Cystic Fibrosis...",
    epigenetica_title: "Epigenetics",
    epigenetica_desc: "Query about epigenetic mechanisms and regulation.",
    epigenetica_input_label: "Epigenetic mechanism or concept",
    epigenetica_placeholder: "e.g., DNA Methylation, Imprinting...",
    section_admin_title: "📊 Admin & Metrics",
    analytics_title: "Analytics Dashboard",
    analytics_desc: "View usage metrics and user feedback.",
    feedback_button: "Give Feedback",
    feedback_title: "Your opinion matters",
    feedback_desc: "How would you rate this response?",
    feedback_submit: "Submit Feedback",
    feedback_success: "Thank you for your feedback!",
    feedback_provider_invite: "You can also provide specific feedback for the AI Agent provider, if you find it appropriate.",
  }
};

export const SIDEBAR_STRUCTURE: Section[] = [
  { id: 'assistance', title: 'section_assistance_title', modules: ['asistente', 'simulador', 'reuniones'] },
  { id: 'analysis', title: 'section_analysis_title', modules: ['evaluador', 'interprete', 'generador'] },
  { id: 'query', title: 'section_query_title', modules: ['genes', 'proteinas', 'vias_de_señalizacion', 'patologias', 'epigenetica'] },
  { id: 'education', title: 'section_education_title', modules: ['glosario'] },
  { id: 'admin', title: 'section_admin_title', modules: ['analytics'] }
];

export const MODULES: Record<string, Module> = {
  asistente: {
    id: 'asistente',
    title: 'asistente_title',
    desc: 'asistente_desc',
    icon: 'MessageSquare',
    inputLabel: 'asistente_input_label',
    placeholder: 'asistente_placeholder',
    policy: {
      purpose: 'Responder consultas generales de genética humana, biomédica y educativa dentro del dominio permitido.',
      scope: 'Conceptos generales, herencia, pruebas genéticas.',
      allowed_domain_statuses: ['valid_genetics', 'adjacent_biomed', 'ambiguous'],
      allowed_intents: ['general_genetics_assistance', 'education_query', 'bibliography_query', 'gene_query', 'protein_query', 'pathway_query', 'genetic_pathology_query', 'epigenetics_query', 'glossary_query'],
      allowed_topics: ['herencia', 'ADN', 'mutaciones', 'consejo genético', 'tecnologías de secuenciación'],
      prohibited_topics: ['sports', 'politics', 'general_history', 'finance', 'entertainment', 'non_biomedical_general_knowledge'],
      allowed_tools: ['pubmed_search', 'pubmed_get_article', 'pubmed_resolve_citation', 'omim_search_entity', 'omim_get_entry', 'hpo_normalize_terms', 'glossary_lookup'],
      output_format: 'structured_answer_card',
      fallback_behavior: {
        out_of_domain: 'reject',
        adjacent_biomed: 'answer_with_scope_warning',
        ambiguous: 'ask_reformulation'
      },
      rejection_type: 'educational',
      depth: 'intermediate'
    }
  },
  evaluador: {
    id: 'evaluador',
    title: 'evaluador_title',
    desc: 'evaluador_desc',
    icon: 'ShieldCheck',
    policy: {
      purpose: 'Ofrecer una evaluación preliminar orientativa basada en fenotipos, hallazgos y contexto genético.',
      scope: 'Criterios clínicos para derivación a genética.',
      allowed_domain_statuses: ['valid_genetics', 'adjacent_biomed', 'ambiguous'],
      allowed_intents: ['preliminary_evaluation', 'genetic_pathology_query', 'gene_query', 'bibliography_query'],
      allowed_topics: ['signos de alerta', 'antecedentes familiares', 'dismorfología', 'retraso del desarrollo'],
      prohibited_topics: ['definitive_diagnosis', 'sports', 'politics', 'finance', 'non_biomedical_general_knowledge'],
      allowed_tools: ['hpo_normalize_terms', 'rank_disorders_by_phenotype', 'omim_search_entity', 'omim_get_entry', 'pubmed_search'],
      output_format: 'preliminary_evaluation_card',
      fallback_behavior: {
        out_of_domain: 'reject',
        adjacent_biomed: 'clarify_then_answer_if_relevant',
        ambiguous: 'ask_reformulation'
      },
      rejection_type: 'strict',
      depth: 'expert'
    }
  },
  interprete: {
    id: 'interprete',
    title: 'interprete_title',
    desc: 'interprete_desc',
    icon: 'FileText',
    inputLabel: 'interprete_input_label',
    placeholder: 'interprete_placeholder',
    policy: {
      purpose: 'Interpretar reportes genéticos de forma estructurada, explicativa y no definitiva.',
      scope: 'Variantes, nomenclatura HGVS, clasificación ACMG.',
      allowed_domain_statuses: ['valid_genetics', 'adjacent_biomed', 'ambiguous'],
      allowed_intents: ['report_interpretation', 'glossary_query', 'gene_query', 'bibliography_query'],
      allowed_topics: ['VCF', 'HGVS', 'ACMG', 'clínica asociada a variantes'],
      prohibited_topics: ['sports', 'politics', 'finance', 'non_biomedical_general_knowledge'],
      allowed_tools: ['parse_report_input', 'extract_report_entities', 'omim_search_entity', 'omim_get_entry', 'pubmed_search', 'glossary_lookup'],
      output_format: 'report_interpretation_card',
      fallback_behavior: {
        out_of_domain: 'reject',
        adjacent_biomed: 'clarify_then_answer_if_relevant',
        ambiguous: 'ask_reformulation'
      },
      rejection_type: 'strict',
      depth: 'expert'
    }
  },
  genes: {
    id: 'genes',
    title: 'genes_title',
    desc: 'genes_desc',
    icon: 'Dna',
    inputLabel: 'genes_input_label',
    placeholder: 'genes_placeholder',
    policy: {
      purpose: 'Responder consultas centradas en genes humanos, función, asociaciones fenotípicas y relevancia clínica.',
      scope: 'Locus, función, expresión, asociaciones.',
      allowed_domain_statuses: ['valid_genetics', 'adjacent_biomed', 'ambiguous'],
      allowed_intents: ['gene_query', 'bibliography_query', 'education_query', 'glossary_query'],
      allowed_topics: ['símbolos de genes', 'coordenadas genómicas', 'dominios funcionales'],
      prohibited_topics: ['sports', 'politics', 'general_history', 'non_biomedical_general_knowledge'],
      allowed_tools: ['omim_search_entity', 'omim_get_entry', 'pubmed_search', 'pubmed_get_article', 'glossary_lookup'],
      output_format: 'gene_card',
      fallback_behavior: {
        out_of_domain: 'reject',
        adjacent_biomed: 'redirect_or_clarify',
        ambiguous: 'ask_reformulation'
      },
      rejection_type: 'educational',
      depth: 'intermediate'
    }
  },
  proteinas: {
    id: 'proteinas',
    title: 'proteinas_title',
    desc: 'proteinas_desc',
    icon: 'Shapes',
    inputLabel: 'proteinas_input_label',
    placeholder: 'proteinas_placeholder',
    policy: {
      purpose: 'Explicar función, estructura, interacción y relevancia biomédica de proteínas relacionadas con genética.',
      scope: 'Estructura, función, modificaciones post-traduccionales.',
      allowed_domain_statuses: ['valid_genetics', 'adjacent_biomed', 'ambiguous'],
      allowed_intents: ['protein_query', 'bibliography_query', 'education_query', 'glossary_query'],
      allowed_topics: ['UniProt ID', 'dominios PDB', 'interacciones proteína-proteína'],
      prohibited_topics: ['sports', 'politics', 'finance', 'non_biomedical_general_knowledge'],
      allowed_tools: ['protein_lookup', 'pubmed_search', 'pubmed_get_article', 'glossary_lookup'],
      output_format: 'protein_card',
      fallback_behavior: {
        out_of_domain: 'reject',
        adjacent_biomed: 'redirect_or_clarify',
        ambiguous: 'ask_reformulation'
      },
      rejection_type: 'educational',
      depth: 'intermediate'
    }
  },
  vias_de_señalizacion: {
    id: 'vias_de_señalizacion',
    title: 'vias_de_señalizacion_title',
    desc: 'vias_de_señalizacion_desc',
    icon: 'Waypoints',
    inputLabel: 'vias_de_señalizacion_input_label',
    placeholder: 'vias_de_señalizacion_placeholder',
    policy: {
      purpose: 'Explicar vías de señalización, interacciones moleculares e implicancias genéticas o patológicas.',
      scope: 'Cascadas, regulación, crosstalk.',
      allowed_domain_statuses: ['valid_genetics', 'adjacent_biomed', 'ambiguous'],
      allowed_intents: ['pathway_query', 'education_query', 'bibliography_query', 'glossary_query'],
      allowed_topics: ['KEGG', 'Reactome', 'redes de señalización'],
      prohibited_topics: ['sports', 'politics', 'general_history', 'non_biomedical_general_knowledge'],
      allowed_tools: ['pathway_lookup', 'pubmed_search', 'pubmed_get_article', 'glossary_lookup'],
      output_format: 'pathway_card',
      fallback_behavior: {
        out_of_domain: 'reject',
        adjacent_biomed: 'redirect_or_clarify',
        ambiguous: 'ask_reformulation'
      },
      rejection_type: 'educational',
      depth: 'intermediate'
    }
  },
  glosario: {
    id: 'glosario',
    title: 'glosario_title',
    desc: 'glosario_desc',
    icon: 'Book',
    inputLabel: 'glosario_input_label',
    placeholder: 'glosario_placeholder',
    policy: {
      purpose: 'Definir y explicar términos de genética de forma breve, precisa y didáctica.',
      scope: 'Términos técnicos y médicos en genética.',
      allowed_domain_statuses: ['valid_genetics', 'adjacent_biomed', 'ambiguous'],
      allowed_intents: ['glossary_query', 'education_query'],
      allowed_topics: ['definiciones', 'etimología', 'contexto de uso'],
      prohibited_topics: ['sports', 'politics', 'finance', 'non_biomedical_general_knowledge'],
      allowed_tools: ['glossary_lookup', 'pubmed_search'],
      output_format: 'glossary_entry',
      fallback_behavior: {
        out_of_domain: 'reject',
        adjacent_biomed: 'redirect_or_clarify',
        ambiguous: 'ask_reformulation'
      },
      rejection_type: 'educational',
      depth: 'basic'
    }
  },
  simulador: {
    id: 'simulador',
    title: 'simulador_title',
    desc: 'simulador_desc',
    icon: 'Users',
    policy: {
      purpose: 'Simular escenarios de consejería genética con enfoque educativo y comunicacional.',
      scope: 'Escenarios de comunicación, empatía, ética.',
      allowed_domain_statuses: ['valid_genetics', 'ambiguous'],
      allowed_intents: ['genetic_counseling_simulation', 'education_query', 'glossary_query'],
      allowed_topics: ['escenarios de consejo', 'técnicas de comunicación', 'dilemas éticos'],
      prohibited_topics: ['definitive_medical_advice', 'non_genetic_general_conversation', 'sports', 'politics', 'finance'],
      allowed_tools: ['glossary_lookup', 'generate_case_simulation', 'communication_guidance', 'omim_search_entity'],
      output_format: 'structured_case_dialogue',
      fallback_behavior: {
        out_of_domain: 'reject',
        adjacent_biomed: 'redirect_or_clarify',
        ambiguous: 'ask_reformulation'
      },
      rejection_type: 'redirection',
      depth: 'intermediate'
    }
  },
  reuniones: {
    id: 'reuniones',
    title: 'reuniones_title',
    desc: 'reuniones_desc',
    icon: 'Mic',
    inputLabel: 'reuniones_input_label',
    placeholder: 'reuniones_placeholder',
    policy: {
      purpose: 'Asistir en reuniones académicas, clínicas o docentes relacionadas con genética.',
      scope: 'Evidencia rápida, guías clínicas, asociaciones fenotipo-genotipo.',
      allowed_domain_statuses: ['valid_genetics', 'adjacent_biomed', 'ambiguous'],
      allowed_intents: ['meeting_support', 'bibliography_query', 'education_query', 'gene_query', 'protein_query', 'pathway_query', 'genetic_pathology_query'],
      allowed_topics: ['guías de práctica clínica', 'evidencia reciente', 'asociaciones raras'],
      prohibited_topics: ['sports', 'politics', 'general_business_unrelated_to_genetics'],
      allowed_tools: ['pubmed_search', 'pubmed_get_article', 'omim_search_entity', 'omim_get_entry', 'build_meeting_brief', 'glossary_lookup'],
      output_format: 'meeting_brief',
      fallback_behavior: {
        out_of_domain: 'reject',
        adjacent_biomed: 'answer_with_scope_warning',
        ambiguous: 'ask_reformulation'
      },
      rejection_type: 'strict',
      depth: 'expert'
    }
  },
  generador: {
    id: 'generador',
    title: 'generador_title',
    desc: 'generador_desc',
    icon: 'Mail',
    policy: {
      purpose: 'Generar informes genéticos estructurados con trazabilidad y referencias verificadas.',
      scope: 'Traducción de lenguaje técnico a lenguaje comprensible.',
      allowed_domain_statuses: ['valid_genetics', 'adjacent_biomed', 'ambiguous'],
      allowed_intents: ['report_generation', 'bibliography_query', 'gene_query', 'genetic_pathology_query'],
      allowed_topics: ['redacción empática', 'explicación de resultados', 'pasos a seguir'],
      prohibited_topics: ['sports', 'politics', 'finance', 'non_biomedical_general_knowledge'],
      allowed_tools: ['assemble_report', 'format_report_sections', 'pubmed_search', 'pubmed_resolve_citation', 'omim_search_entity', 'omim_get_entry'],
      output_format: 'structured_report',
      fallback_behavior: {
        out_of_domain: 'reject',
        adjacent_biomed: 'redirect_or_clarify',
        ambiguous: 'ask_reformulation'
      },
      rejection_type: 'strict',
      depth: 'intermediate'
    }
  },
  patologias: {
    id: 'patologias',
    title: 'patologias_title',
    desc: 'patologias_desc',
    icon: 'AlertCircle',
    inputLabel: 'patologias_input_label',
    placeholder: 'patologias_placeholder',
    policy: {
      purpose: 'Describir patologías genéticas, patrones de herencia, genes asociados y bibliografía relevante.',
      scope: 'Fenotipo, modo de herencia, prevalencia, genes causales.',
      allowed_domain_statuses: ['valid_genetics', 'adjacent_biomed', 'ambiguous'],
      allowed_intents: ['genetic_pathology_query', 'bibliography_query', 'education_query', 'glossary_query'],
      allowed_topics: ['síndromes genéticos', 'enfermedades raras', 'herencia mendeliana'],
      prohibited_topics: ['sports', 'politics', 'finance', 'non_biomedical_general_knowledge'],
      allowed_tools: ['omim_search_entity', 'omim_get_entry', 'pubmed_search', 'pubmed_get_article', 'glossary_lookup'],
      output_format: 'pathology_card',
      fallback_behavior: {
        out_of_domain: 'reject',
        adjacent_biomed: 'answer_with_scope_warning',
        ambiguous: 'ask_reformulation'
      },
      rejection_type: 'educational',
      depth: 'expert'
    }
  },
  epigenetica: {
    id: 'epigenetica',
    title: 'epigenetica_title',
    desc: 'epigenetica_desc',
    icon: 'Globe',
    inputLabel: 'epigenetica_input_label',
    placeholder: 'epigenetica_placeholder',
    policy: {
      purpose: 'Explicar mecanismos epigenéticos, regulación génica y relaciones con enfermedad o desarrollo.',
      scope: 'Metilación, modificación de histonas, imprinting.',
      allowed_domain_statuses: ['valid_genetics', 'adjacent_biomed', 'ambiguous'],
      allowed_intents: ['epigenetics_query', 'bibliography_query', 'education_query', 'glossary_query'],
      allowed_topics: ['mecanismos epigenéticos', 'influencia ambiental', 'enfermedades por imprinting'],
      prohibited_topics: ['sports', 'politics', 'finance', 'non_biomedical_general_knowledge'],
      allowed_tools: ['pubmed_search', 'pubmed_get_article', 'glossary_lookup'],
      output_format: 'epigenetics_card',
      fallback_behavior: {
        out_of_domain: 'reject',
        adjacent_biomed: 'answer_with_scope_warning',
        ambiguous: 'ask_reformulation'
      },
      rejection_type: 'educational',
      depth: 'intermediate'
    }
  },
  analytics: {
    id: 'analytics',
    title: 'analytics_title',
    desc: 'analytics_desc',
    icon: 'BarChart3',
    policy: {
      purpose: 'Visualizar métricas agregadas de feedback y uso del sistema.',
      scope: 'Métricas, analítica, promedios.',
      allowed_domain_statuses: ['valid_genetics'],
      allowed_intents: ['analytics_query'],
      allowed_topics: ['satisfacción', 'uso por modo', 'tendencias'],
      prohibited_topics: ['pii_exposure'],
      allowed_tools: ['get_global_stats', 'get_mode_stats'],
      output_format: 'analytics_dashboard',
      fallback_behavior: {
        out_of_domain: 'reject',
        adjacent_biomed: 'reject',
        ambiguous: 'reject'
      },
      rejection_type: 'strict',
      depth: 'expert'
    }
  }
};
